In [35]:
import numpy as np
print("Hello World")

Hello World


In [36]:
newList = [1,23,4,5,7]
np.array(newList)


array([ 1, 23,  4,  5,  7])

## numpy methods 

In [37]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,10,2) #Step Size is two 0,2,4..

array([0, 2, 4, 6, 8])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((3,9)) #Three list that each has nine zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.ones( (3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

In [42]:
np.linspace(0,20,5)#select 5 number between 0-20 and this numbers must have equals distance

array([ 0.,  5., 10., 15., 20.])

In [43]:
np.eye(10) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random


In [44]:
np.random.randn(3,3)

array([[-0.76690242,  1.71293441, -1.52615342],
       [ 0.20739185, -0.29832228, -0.10689872],
       [-0.42350845, -1.29143681, -0.15419073]])

In [45]:
np.random.randint(1,10)

9

In [46]:
np.random.randint(1,150,5)

array([ 35,  55,  14, 112,  67])

## Numpy arrays own methods

In [55]:
myNumpyArray = np.arange(30)
myNumpyArray.reshape(5,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
myNumpyArray.max()

29

In [61]:
myNumpyArray.min()

0

In [71]:
myRandomArray = np.random.randint(0,100,15)
myRandomArray

array([65, 97, 19, 93, 48, 63, 87, 81, 64, 96, 12, 68,  0,  2, 67])

In [72]:
myRandomArray.max()

97

In [73]:
myRandomArray.argmax()

1

In [75]:
myRandomArray.min()

0

In [76]:
myRandomArray.argmin()

12

In [80]:
reshapedArray = myNumpyArray.reshape(5,6)
reshapedArray
reshapedArray.shape

(5, 6)