In [1]:
import numpy as np



In [3]:
myArray = np.arange(15)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [5]:
myArray[3:5]

array([3, 4])

In [6]:
myArray[3:8] = -5

In [7]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
otherArray = np.arange(24)
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingArray = otherArray[4:7]


In [15]:
slicingArray[:] = 700

In [16]:
slicingArray

array([700, 700, 700])

In [17]:
otherArray

array([  0,   1,   2,   3, 700, 700, 700,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
otherArray2 = np.arange(24)


In [21]:
exampleArray = otherArray2.copy()

In [24]:
exampleArraySlicing = exampleArray[4:8]
exampleArraySlicing[:]  = 800

In [25]:
exampleArray

array([  0,   1,   2,   3, 800, 800, 800, 800,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
otherArray2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [29]:
theList = [[1,23,4,6],[3,45,7,84],[324,32,21,75]]

exapmleMatrixArray = np.array(theList)
exapmleMatrixArray

array([[  1,  23,   4,   6],
       [  3,  45,   7,  84],
       [324,  32,  21,  75]])

In [30]:
exapmleMatrixArray[0]

array([ 1, 23,  4,  6])

In [32]:
exapmleMatrixArray[0][2]

4

In [33]:
exapmleMatrixArray[0,2]

4

In [36]:
exapmleMatrixArray[0:,2]

array([ 4,  7, 21])

In [37]:
exapmleMatrixArray[0:,2:]

array([[ 4,  6],
       [ 7, 84],
       [21, 75]])

In [39]:
exapmleMatrixArray[2,1:]

array([32, 21, 75])

In [41]:
exapmleMatrixArray[[0,1]]

array([[ 1, 23,  4,  6],
       [ 3, 45,  7, 84]])

## Operations

In [43]:
newArray = np.random.randint(0,100,25)
newArray

array([83,  5, 66, 52, 75, 86, 30, 22, 79,  7, 34, 94, 74, 73, 71, 87, 51,
       19, 22, 89, 98,  6, 32, 45, 86])

In [44]:
newArray > 24

array([ True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True])

In [45]:
booleanArray = newArray > 24
booleanArray

array([ True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True])

In [47]:
newArray[booleanArray]

array([83, 66, 52, 75, 86, 30, 79, 34, 94, 74, 73, 71, 87, 51, 89, 98, 32,
       45, 86])

In [50]:
lastArray = np.arange(25)


In [53]:
lastArray 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [55]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [56]:
lastArray.max()

24